AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - quarkus-aws-lambda-rest-1.0-SNAPSHOT
Globals:
  Api:
    EndpointConfiguration: REGIONAL


Resources:
  QuarkusAwsLambdaRest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java17
      CodeUri: target/function.zip
      MemorySize: 2048
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref NoteDDBTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentDDBTable
      Timeout: 150
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  NoteDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Note
      PrimaryKey:
        Name: id
        Type: Number
  CommentDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Comment
      PrimaryKey:
        Name: id
        Type: Number

Outputs:
  QuarkusAwsLambdaRestApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: QuarkusAwsLambdaRestApi
